name: pdf_summarizer
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - python-dotenv
  - requests
  - jupyterlab
  - pip:
    - openai
    - ollama
    - PyPDF2
    - streamlit
